// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveTraincim2 = NULL;
SpeedController* RobotMap::driveTraincim1 = NULL;
RobotDrive* RobotMap::driveTrainRobotDrive = NULL;
SpeedController* RobotMap::winchcim3 = NULL;
SpeedController* RobotMap::winchcim4 = NULL;
Encoder* RobotMap::winchencoder = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	driveTraincim2 = new Jaguar(1, 2);
	lw->AddActuator("DriveTrain", "cim2", (Jaguar*) driveTraincim2);
	
	driveTraincim1 = new Jaguar(1, 1);
	lw->AddActuator("DriveTrain", "cim1", (Jaguar*) driveTraincim1);
	
	driveTrainRobotDrive = new RobotDrive(driveTraincim1, driveTraincim2);
	
	driveTrainRobotDrive->SetSafetyEnabled(true);
        driveTrainRobotDrive->SetExpiration(0.1);
        driveTrainRobotDrive->SetSensitivity(0.5);
        driveTrainRobotDrive->SetMaxOutput(1.0);
        
	winchcim3 = new Jaguar(1, 3);
	lw->AddActuator("Winch", "cim3", (Jaguar*) winchcim3);
	
	winchcim4 = new Jaguar(1, 4);
	lw->AddActuator("Winch", "cim4", (Jaguar*) winchcim4);
	
	winchencoder = new Encoder(1, 1, 1, 2, false, Encoder::k4X);
	lw->AddSensor("Winch", "encoder", winchencoder);
	winchencoder->SetDistancePerPulse(1.0);
        winchencoder->SetPIDSourceParameter(Encoder::kRate);
        winchencoder->Start();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
