// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RelayHold.h"
#include "../Robotmap.h"
#include "../Commands/MoveRelay.h"
#include "SmartDashboard/SmartDashboard.h"
int stopForwardOld = 0;
int stopBackOld = 0;
RelayHold::RelayHold() :
	Subsystem("Relay") {
	spike1 = RobotMap::relaySpike1;
	limitSwitch1 = RobotMap::relayLimitSwitch1;
	limitSwitch2 = RobotMap::relayLimitSwitch2;
	baseLimit = RobotMap::relayLimitSwitch3; //Limit switch at the base of the winch
}

void RelayHold::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	SetDefaultCommand(new MoveRelay());

	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void RelayHold::MoveForward(Joystick* stick) {
	bool debug = false;
	int stopBack = limitSwitch2->Get();
	int stopForward = limitSwitch1->Get();
	if (stopForward != stopForwardOld || stopBack != stopBackOld && debug
			== true) {
		//if forward limit switch changes or back limit switch changes
		stopForwardOld = stopForward;
		stopBackOld = stopBack;
		printf("Forward %d\nBack %d\n", stopForward, stopBack);
	}
	if (stick->GetRawButton(1) == true && stopBack == 1) {
		spike1->Set(Relay::kOn);
		spike1->Set(Relay::kForward);
		printf("It's going Backward! \n");
	} else if (stick->GetRawButton(2) == true && stopForward == 1) {
		spike1->Set(Relay::kOn);
		spike1->Set(Relay::kReverse);
		printf("It's going Forward! \n");
	} else {
		spike1->Set(Relay::kOff);
	}

}

void RelayHold::Stop() {
	spike1->Set(Relay::kOff);
}

// Put methods for controlling this subsystem
// here. Call these from Commands.
