// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Winch.h"
#include "../Robotmap.h"
#include "../Commands/MoveWinch.h"
#include "SmartDashboard/SmartDashboard.h"
//#include "auto_encoders.h"


Winch::Winch() : Subsystem("Winch") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	cim3 = RobotMap::winchcim3;
	cim4 = RobotMap::winchcim4;
	encoder = RobotMap::winchencoder;
	baseLimit = RobotMap::relayLimitSwitch3; //Limit switch at the base of the winch
    AndyMark= RobotMap::AndyMark;
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Winch::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new MoveWinch());
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void Winch::Move(Joystick* stick){
			
	
	//printf("Base Limit %d and Encoder %f \n",baseLimit->Get(), encoder->GetDistance());

	//if the y axis of the stick has a value greater than 0.025 and less than -0.025
		if(stick->GetY() > 0.025 || stick->GetY() < -0.025){
		//sets the speed of the motors to 75% of the value of the stick
			cim3->Set(stick->GetY()*0.75);
			cim4->Set(stick->GetY()*0.75);
		} else if(stick->GetY() < 0.1 && stick->GetY() > -0.1){
			cim3->Set(0);
			cim4->Set(0);
		}
		
		
		if (stick->GetRawButton(6)==true) {
			AndyMark->Set(0.25);
		}
		else if (stick->GetRawButton(7)==true) {
		AndyMark->Set(-0.25);
		}
		else {
			AndyMark->Set(0.0);
		}
		
		
}

void Winch::Stop(){
	cim3->Set(0);
	cim4->Set(0);
	AndyMark->Set(0);
	//encoder->Stop(); //Stop the encoder
	//bencoder->Reset(); //Reset the encoder
}
/*
double Winch::Read(){
	dsLCD->Printf(DriverStationLCD::kUser_Line1,1,"Encoder: %f",encoder->GetDistance());
	dsLCD->UpdateLCD();	
}
*/

